#CFLAGS+=-Wall -Wextra -ansi -pedantic -g
CFLAGS+=-Wall -Wextra -std=c11 -pedantic -g

objects = const_ptr \
		  dynmem \
		  ptr_arith \
		  ptr_basics \
		  ptr_vs_array \
		  sizeof \
		  strings

all: $(objects)

clean:
	$(RM) $(objects)
